In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv("../data/Delivery_Logistics.csv")

data.head()

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost
0,250.99,delhivery,automobile parts,bike,same day,west,clear,297.0,46.96,1970-01-01 00:00:00.000000008,1970-01-01 00:00:00.000000008,no,delivered,3,1632.7206
1,250.99,xpressbees,cosmetics,ev van,express,central,cold,89.6,47.39,1970-01-01 00:00:00.000000002,1970-01-01 00:00:00.000000003,no,delivered,5,640.1700
2,250.99,shadowfax,groceries,truck,two day,east,rainy,273.5,26.89,1970-01-01 00:00:00.000000010,1970-01-01 00:00:00.000000016,no,delivered,4,1448.1700
3,250.99,dhl,electronics,ev van,same day,east,cold,269.7,12.69,1970-01-01 00:00:00.000000006,1970-01-01 00:00:00.000000008,no,delivered,3,1486.5700
4,250.99,dhl,clothing,van,two day,north,foggy,256.7,37.02,1970-01-01 00:00:00.000000009,1970-01-01 00:00:00.000000016,no,delivered,4,1394.5600

In [2]:
data.isnull().sum()

delivery_id            0
delivery_partner       0
package_type           0
vehicle_type           0
delivery_mode          0
region                 0
weather_condition      0
distance_km            0
package_weight_kg      0
delivery_time_hours    0
expected_time_hours    0
delayed                0
delivery_status        0
delivery_rating        0
delivery_cost          0
dtype: int64

In [3]:
data.duplicated().sum()

0

In [4]:
data = data.drop_duplicates()

In [5]:
data["delivery_time_hours"] = pd.to_datetime(
    data["delivery_time_hours"]
).dt.nanosecond

data["expected_time_hours"] = pd.to_datetime(
    data["expected_time_hours"]
).dt.nanosecond

In [6]:
data.dtypes

delivery_id            float64
delivery_partner        object
package_type            object
vehicle_type            object
delivery_mode           object
region                  object
weather_condition       object
distance_km            float64
package_weight_kg      float64
delivery_time_hours      int32
expected_time_hours      int32
delayed                 object
delivery_status         object
delivery_rating          int64
delivery_cost          float64
dtype: object

In [7]:
data.describe()

,delivery_id,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delivery_rating,delivery_cost
count,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,12500.500000,150.390436,25.145898,6.248040,13.107680,3.666000,864.944579
std,7212.732314,86.409745,14.368663,3.140935,7.559024,1.149964,435.712593
min,250.990000,3.600000,0.670000,0.000000,2.000000,1.000000,95.667400
25%,6250.750000,75.900000,12.680000,4.000000,8.000000,3.000000,490.800000
50%,12500.500000,151.000000,25.145000,6.000000,8.000000,4.000000,867.535000
75%,18750.250000,224.900000,37.660000,8.000000,16.000000,5.000000,1237.910000
max,24750.010000,297.100000,49.520000,19.000000,24.000000,5.000000,1632.720600

In [8]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

numeric_columns = [
    "distance_km",
    "package_weight_kg",
    "delivery_time_hours",
    "expected_time_hours",
    "delivery_rating",
    "delivery_cost"
]

data[numeric_columns] = scaler.fit_transform(
    data[numeric_columns]
)